#!/bin/sh
# Setup a machine for Sublime Text 2

sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 2/Packages
if [ ! -d "$sublime_dir/User.backup" ]; then
  echo Updating User files
  mv "$sublime_dir/User" "$sublime_dir/User.backup"
  cp -R "$ZSH/sublime2/User" "$sublime_dir"
fi

# Grab the Soda theme
if [ ! -d "${sublime_dir}/Theme - Soda" ]; then
  echo Cloning soda theme
  cd "$sublime_dir"
  git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
fi
